### ISSUE TITLE
Plan for Saturday:

### ISSUE THREAD

**Issue by nichelicorn** [nichelicorn/whats-cookin#50]
- [x] Complete Project board
- [x] Nichele Iteration One
- [x] Lourdes Iteration Two and Three
- [x] Lourdes Create Backwards Plan 
- [x] Find design inspiration

**Comment by nichelicorn** [comment]
* Design Inspirations 👩‍🎨
![WhatsCookin’ 3](https://user-images.githubusercontent.com/63027000/118407502-44986e00-b63e-11eb-9536-54f39c9bd054.jpg)
![WhatsCookin’ 4](https://user-images.githubusercontent.com/63027000/118407509-4bbf7c00-b63e-11eb-8393-73c0e02d08e3.jpg)
![WhatsCookin’ 5](https://user-images.githubusercontent.com/63027000/118407515-51b55d00-b63e-11eb-83c6-9859f65906e9.jpg)

**Comment by nichelicorn** [comment]
* links: 
* https://cooking.nytimes.com
* https://www.epicurious.com
* https://www.foodnetwork.com

**Comment by mendozalourdes** [comment]
* links
* https://www.budgetbytes.com/
* https://foodgawker.com/
* https://www.simplyrecipes.com/
